### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ewhal** [NyaaPantsu/scrapers#6]
- [ ] Scrape torrents that are a week old hourly
- [ ] Scrape all torrents daily
- [ ] Scrape filelists if don't exist
- [ ] Scrape mediainfo
- [ ] Torrent file generation
